name: StaffChannel
main: me.SavageUser.StaffChannel.Core
authors:
  - SavageUser
  - ItsVollx
version: 1.2

commands:
  adminchat:
    aliases: [ac]
    description: Send a message to online administrators.
  staffchat:
    aliases: [sc]
    description: Send a message to online staff members.
